const fs = require('fs');
const path = require('path');

const content = {
  "docs/index.md": `# X32 Masterclass & Operational Handbook\n\nBienvenido a la documentación técnica y operativa para la mesa de mezclas Behringer X32.\n\n## Índice del Curso\n\n- [Módulo 1: Flujo de Señal](./module-1-signal-flow/01-architecture.md)\n- [Módulo 2: Channel Strip](./module-2-channel-strip/01-preamp-filters.md)\n- [Módulo 3: Buses y Matrix](./module-3-buses-matrix/01-mixbuses-iem.md)\n- [Módulo 4: Rack de FX](./module-4-fx-rack/01-rack-slots.md)\n- [Módulo 5: Flujos de Trabajo](./module-5-workflows/01-virtual-soundcheck.md)\n\n## Flujo de Señal Rápido\nEntrada Analógica -> Preamp -> [Insert Pre] -> HPF/Gate -> [Insert Post] -> EQ -> Compresor -> Fader -> Bus/Main.`,
  "docs/updates/index.md": `# Historial de Actualizaciones\n\nAquí encontrarás las notas de parche y avisos operativos para cada actualización de Firmware de la X32 y Mixing Station, analizados para minimizar riesgos en directo.`,
  
  "docs/module-1-signal-flow/01-architecture.md": `# Arquitectura de la X32\n\nLa X32 tiene 40 entradas de mezcla completas y 25 buses.\n\n## Separación Físico vs Lógico\nEntiende que las entradas físicas (XLR en la parte trasera) son independientes de los canales lógicos (CH 1-32). El ruteo permite asignar cualquier entrada a cualquier canal.\n\n## DSP Interno\nEl DSP maneja el procesamiento de punto flotante a 40-bit internamente, garantizando headroom prácticamente infinito antes del máster.`,
  "docs/module-1-signal-flow/02-user-routing.md": `# User Routing\n\nA partir del firmware V4, Behringer introdujo el "User Routing".\n\n## Bloques de 8 vs User Routing 1:1\nAnteriormente (Pre-v4), el ruteo debía hacerse en bloques rígidos de 8 canales. Ahora, el parcheo permite seleccionar canales uno a uno (1:1), facilitando la mezcla de fuentes locales, stageboxes AES50 y tarjeta USB sin sacrificar entradas.`,
  "docs/module-1-signal-flow/03-gain-staging.md": `# Ajuste de Ganancia (Gain Staging)\n\n## Preamp Analógico vs Trim Digital\n- **Preamp:** Ajusta entre -18 dBFS y -12 dBFS.\n- **Trim (Gain Split):** Permite separar la ganancia analógica del control digital en FOH/Monitores.\n\n## Puntos de Inserción (Tap Points)\n- **IN / LC:** Justo tras la ganancia.\n- **Pre-EQ / Post-EQ:** Antes o después del ecualizador.\n- **Pre-Fader / Post-Fader:** Antes o después del control de volumen.`,

  "docs/module-2-channel-strip/01-preamp-filters.md": `# Preamplificador y Filtros\n\n## Low Cut (HPF)\nUsa siempre el HPF para eliminar el barro (rumble) de bajas frecuencias. Ajusta según la fuente (ej. Voces > 100Hz).\n\n## Polaridad y Enlace Estéreo\n- Invierte polaridad en micrófonos de caja (bottom) o bombo interior.\n- Enlaza (Link) en impares/pares para fuentes estéreo verdaderas.`,
  "docs/module-2-channel-strip/02-gate-expander.md": `# Puerta y Expansor\n\n## Key Filters\nUsa filtros en la cadena lateral de la puerta para que sólo se abra con una frecuencia específica (ej. 60Hz para el bombo).\n\n## Attack, Hold, Release\n- **Bombo:** Ataque muy rápido (1ms), Hold medio (40ms), Release rápido (50ms).\n- **Voces:** Mejor usar un expansor suave en lugar de una puerta estricta para evitar cortes artificiales.`,
  "docs/module-2-channel-strip/03-eq-compression.md": `# EQ y Compresión\n\n## PEQ de 4 Bandas\nEl ecualizador principal soporta modos Shelving, PEQ clásico y VEQ (emulación vintage).\n\n## Sidechain Externo (Ducking)\nAsigna la señal del bombo como clave para comprimir el bajo eléctrico de forma que se "hunda" cada vez que suena el bombo.`,

  "docs/module-3-buses-matrix/01-mixbuses-iem.md": `# Mixbuses y Envíos a IEM\n\n## Sends on Fader\nActiva este modo para crear mezclas de monitores rápidamente usando los faders principales.\n\n## Configuración\nPara cuñas (wedges) o IEMs, configura el bus en *Pre-Fader* o *Post-EQ* para que los cambios de volumen en FOH no afecten a los músicos.`,
  "docs/module-3-buses-matrix/02-matrix-broadcast.md": `# Matrix y Broadcast\n\nLas matrices son "buses de los buses". \n\n## Usos Comunes\n- Mezcla independiente para broadcast / streaming.\n- Envíos a Front-fills o torres de retardo (delay).\n- Proporcionan EQ y limitador independientes del L/R principal.`,
  "docs/module-3-buses-matrix/03-dca-vs-subgroups.md": `# DCA vs Subgrupos\n\n## DCA (Digitally Controlled Amplifier)\nControl remoto de volumen para grupos de canales. No agrupa el audio, por lo que no se le puede aplicar compresión de bus.\n\n## Subgrupos\nAgrupa las señales de audio reales. Ideal para compresión de baterías en paralelo o ecualización grupal de coros.`,

  "docs/module-4-fx-rack/01-rack-slots.md": `# Slots de Rack FX\n\n## Distribución\n- **Slots 1 a 4:** Optimizados para efectos de tiempo (Reverbs, Delays). Típicamente usados como envíos (Send/Return).\n- **Slots 5 a 8:** Diseñados para procesadores de dinámica y ecualización gráfica. Típicamente usados como Inserciones en canales o buses principales.`,
  "docs/module-4-fx-rack/02-emulations.md": `# Emulaciones Clásicas\n\n- **LA-2A (Leisure Compressor):** Óptimo para compresión suave y musical en voces y bajos.\n- **1176 (Ultimo Compressor):** Ataque rapidísimo, ideal para aplastar cajas o paralelos de batería.\n- **Fairchild:** Compresión de bus maestro o subgrupos densos.\n- **TruEQ:** Ecualizador gráfico sin interacción entre bandas adyacentes para afinar salas.`,

  "docs/module-5-workflows/01-virtual-soundcheck.md": `# Prueba de Sonido Virtual\n\n## Flujo USB 32x32\nConecta la tarjeta X-USB al DAW.\n1. Ajusta el ruteo para enviar las señales de los previos locales directamente al USB (Grabación).\n2. Para Virtual Soundcheck, cambia las entradas de los canales de "Local" a "Card 1-32".\n3. Reproduce el multipista y ajusta la mezcla sin necesidad de la banda.`,
  "docs/module-5-workflows/02-scenes-snippets.md": `# Escenas y Snippets\n\n## Escenas\nGuardan el estado total de la consola (excepto configuraciones globales).\n\n## Snippets\nCambios quirúrgicos. Por ejemplo, mutear una sección de canales o cambiar el ruteo de un solo micrófono sin alterar toda la mezcla.\n\n## Parameter Safes\nEvita que ciertos canales o parámetros (ej. el canal del MC o la música de fondo) cambien al cargar una nueva escena.`,
  "docs/module-5-workflows/03-network-osc.md": `# Red y Control OSC\n\n## Configuración Inalámbrica\nConecta la consola a un router Wi-Fi en 5GHz. Usa direcciones IP estáticas para mayor fiabilidad.\n\n## Aplicaciones\n- **X32-Edit:** Control de PC/Mac profundo.\n- **Mixing Station:** Aplicación móvil preferida por su alta personalización en FOH y Monitores.\n\n## OSC (Open Sound Control)\nLa X32 es controlable completamente por OSC enviando paquetes UDP al puerto 10024.`
};

Object.keys(content).forEach(filePath => {
  const fullPath = path.join(__dirname, filePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content[filePath]);
});

console.log('Archivos Markdown generados con éxito.');
